### PR TITLE
docs: added docs into the repo with vitepress for 1.0.0

### PR DESCRIPTION
**Pull request by nathanaelhoun**
#### Description of Change

Added the documentation for Atom inside the repository. It is built to https://atom-documentation.netlify.app/ with Netlify on each push on the `main` branch.

#### Motivation and Context

JS and CSS are hot reloaded from source, so this allows to use the docs as visual testing during development.

### CODE REVIEW

**Comment by nathanaelhoun** [comment]
Documentation is now working with JS and CSS from Atom! :tada: 
I needed to install a little hack for JS hot reloading and bundling in 5ac9b51e927e44b8afdd78f32d6d6d32eb4d725f, which should be temporary :wink:

**Comment by nathanaelhoun** [comment]
@tdelavoux Do you want to keep a version for the JQuery version of Atom, and then update it for the next version without JQuery,
or do we start this new documentation based on the next version without JQuery only?

**Comment by tdelavoux** [comment]
@nathanaelhoun.  JQuery version was a part of development'sproccess to V1.0.0 but there is no reason to maintain a JQ version or leave a bugged early release that include it. I suggest to base documentation on the next version with Vanilla JS and visual improvments. 
Avaiable to discust about it this trajectory if needed.

**Comment by nathanaelhoun** [comment]
Closing as this version of the doc is for the old 1.x.x release. A new PR will be created for the version without JQuery.

**Pull request closed without merging**
